### ISSUE TITLE
androidx.tonyodev.fetch2:xfetch2:3.1.4 - JCenter()

### ISSUE THREAD

**Issue by loria33** [kesha-antonov/react-native-background-downloader#1]
Do you have a work around for androidx.tonyodev.fetch2:xfetch2:3.1.4 being only on Jcenter()

**Comment by pfox72** [comment]
586 think this is a duplicate of https://github.com/tonyofrancis/Fetch/issues/586

**Comment by pfox72** [comment]
I think once tonyofrancis uploads a version of fetch to maven, someone needs to then update background downloader to use that version create a PR. I don't think anyone other than tony can upload to maven, because it needs to be signed correctly, I just don't know enough about it to say for sure though.

**Comment by kesha-antonov** [comment]
> Do you have a work around for androidx.tonyodev.fetch2:xfetch2:3.1.4 being only on Jcenter()

As I understand latest release is on JitPack: https://github.com/tonyofrancis/Fetch/issues/586#issuecomment-954225519

https://jitpack.io/p/tonyofrancis/fetch

Do you have this into `android/build.gradle`?

```
allprojects {
    repositories {
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url(new File(["node", "--print", "require.resolve('react-native/package.json')"].execute().text.trim(), "../android"))
        }
        maven {
            // Android JSC is installed from npm
            url(new File(["node", "--print", "require.resolve('jsc-android/package.json')"].execute().text.trim(), "../dist"))
        }
        mavenCentral {
            // We don't want to fetch react-native from Maven Central as there are
            // older versions over there.
            content {
                excludeGroup "com.facebook.react"
            }
        }

        google()
        jcenter()
        maven { url 'https://www.jitpack.io' }
    }
}
```

<img width="844" alt="Screenshot 2022-02-08 at 19 49 28" src="https://user-images.githubusercontent.com/11584712/153035297-f3c9d2c3-8680-4102-895d-6d6b4da99b6f.png">

**Comment by sebastiangrebe** [comment]
@kesha-antonov I am still getting this problem at the moment. What I get from the other linked issue is that version 2:3.1.6 is on jitpack but react-native-background-downloader is pointing to 2:3.1.4 which is not there. See in the attached screenshot.
![Bildschirmfoto 2022-03-02 um 23 04 37](https://user-images.githubusercontent.com/923505/156430806-e0f3a027-bee7-42dc-8b16-dec76e84015d.png)

Can you provide an update for this?

**Comment by sebastiangrebe** [comment]
Ok got around, I believe had wrong node_modules, just deleted it all together now it is working

**Comment by kesha-antonov** [comment]
> Ok got around, I believe had wrong node_modules, just deleted it all together now it is working

Nice to hear that!

**Comment by kesha-antonov** [comment]
merged PR. now this lib doesn't use jcenter
