### ISSUE TITLE
'metadata' field on DownloadTask is not present in interface, causing typescript warnings

### ISSUE THREAD

**Issue by sjchristi** [kesha-antonov/react-native-background-downloader#1]
The `metadata` field that is a member of the `DownlaodTask` class is not in the `DownloadTask` interface, so you'll end up with warnings in typescript if you try to access it.

**Comment by kesha-antonov** [comment]
Hi,
could you correct ts with PR?

**Comment by kesha-antonov** [comment]
Fixed by https://github.com/kesha-antonov/react-native-background-downloader/pull/20
