### ISSUE TITLE
Build Failed - Android - Could not resolve jitpack Fetch pom

### ISSUE THREAD

**Issue by jasielmacedo** [kesha-antonov/react-native-background-downloader#11]
### Is this a bug report, a feature request, or a question?

Bug Report

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - put an `x` character between the square brackets (`[]`).)

- [X] I have reviewed [the documentation](https://github.com/EkoLabs/react-native-background-downloader/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [X] I have searched for [existing issues](https://github.com/EkoLabs/react-native-background-downloader/issues) and made sure that the problem hasn't already been reported.
- [] I am using [the latest plugin version](https://github.com/EkoLabs/react-native-background-downloader/releases). 
- [X] I am using the latest version of this fork

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Android

### Is the bug related to the native implementation? (NSURLSession on iOS and Fetch on Android)

Probably related to tonyofrancis/Fetch

### Environment

  Environment:
    React: 17.0.2
    React native: 0.67.1
    react-native-background-downloader: 2.4.2

  Target Platform:
    Android (10)
    iOS (13)

### Expected Behavior

Should be able to complete the build task normally

### Actual Behavior

During the build process, the gradle is not able to finish the tasks due to a failure related to one dependency

Log:

```
Execution failed for task ':app:checkQaReleaseAarMetadata'.
> Could not resolve all files for configuration ':app:qaReleaseRuntimeClasspath'.
   > Could not resolve com.github.tonyofrancis.Fetch:xfetch2:3.1.6.
     Required by:
         project :app > project :react-native-background-downloader
      > Could not resolve com.github.tonyofrancis.Fetch:xfetch2:3.1.6.
         > Could not get resource 'https://www.jitpack.io/com/github/tonyofrancis/Fetch/xfetch2/3.1.6/xfetch2-3.1.6.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/tonyofrancis/Fetch/xfetch2/3.1.6/xfetch2-3.1.6.pom'. Received status code 521 from server: 
   > Could not resolve com.github.tonyofrancis.Fetch:xfetch2okhttp:3.1.6.
     Required by:
         project :app > project :react-native-background-downloader
      > Could not resolve com.github.tonyofrancis.Fetch:xfetch2okhttp:3.1.6.
         > Could not get resource 'https://www.jitpack.io/com/github/tonyofrancis/Fetch/xfetch2okhttp/3.1.6/xfetch2okhttp-3.1.6.pom'.
            > Could not GET 'https://www.jitpack.io/com/github/tonyofrancis/Fetch/xfetch2okhttp/3.1.6/xfetch2okhttp-3.1.6.pom'. Received status code 521 from server: 


```
### Steps to Reproduce

1. Start a new react native progres
2. Add this package in the project
3. Try to generate a build for android

**Comment by Mohammad-DH** [comment]
same problem

**Comment by kesha-antonov** [comment]
Closing since android side was rewritten on branch v3 https://github.com/kesha-antonov/react-native-background-downloader/tree/3.0.0
And jitpack is not needed anymore
