### ISSUE TITLE
Permission denied on pull request to this repo

### ISSUE THREAD

**Issue by fivecar** [kesha-antonov/react-native-background-downloader#12]
I'd like to push a PR to fix a small README.md typo, but this is what I get when I try to do so:
```Terminal
$ git push -uf origin platform_docs_typo
fatal: unable to access 'https://github.com/kesha-antonov/react-native-background-downloader.git/': The requested URL returned error: 403
```
Could you LMK if I'm doing something wrong here? I see #10 is open, so there've got to be ways to submit a PR...

**Comment by kesha-antonov** [comment]
Hi!
Yes, you should fork repo on your profile - then you do your changes - then you create PR.

Is that clear?
Let me know if I could help further.

**Comment by fivecar** [comment]
🤦 I've PR'd to a bunch of open source projects; this was such a n00b mistake. Thanks for helping, @kesha-antonov .

**Comment by kesha-antonov** [comment]
Np 👌
