### ISSUE TITLE
option to disable Fetch's Parallel downloading?

### ISSUE THREAD

**Issue by willxy** [kesha-antonov/react-native-background-downloader#14]
### Is this a bug report, a feature request, or a question?

Feature request

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - put an `x` character between the square brackets (`[]`).)

- [x] I have reviewed [the documentation](https://github.com/EkoLabs/react-native-background-downloader/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/EkoLabs/react-native-background-downloader/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/EkoLabs/react-native-background-downloader/releases).

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Android

### Is the bug related to the native implementation? (NSURLSession on iOS and Fetch on Android)

Fetch

### Environment

(Write your answer here.)

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add logs!)

### Steps to Reproduce

(Write your steps so that anyone can reproduce the issue in the Snack demo you provided.)

1.
2.
3.

We're running into some issues related to Fetch's PARALLEL FileDownloaderType, which RNBD enables by default.

Is it possible to expose some option in RNBD that would allow choosing the SEQUENTIAL downloaderType instead of the PARALLEL downloaderType?

Thanks,
Will

**Comment by kesha-antonov** [comment]
Hi

Could you add more details to your feature request?

rn you can use sequential downloads with js code

Just use

`download().done(() => download next file ... )`

**Comment by kesha-antonov** [comment]
Seems like you're talking about android side?

https://github.com/kesha-antonov/react-native-background-downloader/blob/master/android/src/main/java/com/eko/RNBackgroundDownloaderModule.java#L99

Could you elaborate more your use case and why it is not working for you rn

**Comment by willxy** [comment]
Yes android, as I mentioned.  Indeed, that line in RNBackgroundDownloaderModule.java that chooses Fetch's parallel downloader.

In our case:

- The download url is a php API endpoint
- The first problem was that Fetch didn't seem to recognize that the endpoint didn't support parallel downloads, and initiated 6 parallel requests anyway.  Since the endpoint didn't support Range headers, each request sent the file from the beginning.  Fetch assembled the data from the 6 requests and the result was a file that had the first 1/6 of the file repeated 6 times.  (Ie, we were getting corrupted downloads) (see also [Fetch #419](https://github.com/tonyofrancis/Fetch/issues/419) )
-  We've added support for Range headers in the API endpoint, but it looks like Fetch is not sending complete ranges for each segment, eg sending Range headers of:
   - Range: 0-
   - Range: 336994-
   - Range: 1684970-
   - etc
- ie without an end to the range, much more data is being transferred than is necessary (my math says 3.5x the size of the file) with eg the possibility of using up customers' data unnecessarily (see also [Fetch #651](https://github.com/tonyofrancis/Fetch/issues/651) )

As a result, at this point we'd rather move forward with just using Fetch's SEQUENTIAL downloader rather than using its PARALLEL downloader.  So I'm exploring what avenues we might have for doing that.  Obviously I could build from my own fork of RNBD with the downloadertype changed, but it's not my first choice. I was hoping there might be a way to pass an argument from the RN side, to change the downloader type that gets selected in the RNBackgroundDownloaderModule() routine.

**Comment by kesha-antonov** [comment]
> Yes android, as I mentioned. Indeed, that line in RNBackgroundDownloaderModule.java that chooses Fetch's parallel downloader.
> 
> In our case:
> 
> * The download url is a php API endpoint
> * The first problem was that Fetch didn't seem to recognize that the endpoint didn't support parallel downloads, and initiated 6 parallel requests anyway.  Since the endpoint didn't support Range headers, each request sent the file from the beginning.  Fetch assembled the data from the 6 requests and the result was a file that had the first 1/6 of the file repeated 6 times.  (Ie, we were getting corrupted downloads) (see also [Fetch #419](https://github.com/tonyofrancis/Fetch/issues/419) )
> * We've added support for Range headers in the API endpoint, but it looks like Fetch is not sending complete ranges for each segment, eg sending Range headers of:
>   
>   * Range: 0-
>   * Range: 336994-
>   * Range: 1684970-
>   * etc
> * ie without an end to the range, much more data is being transferred than is necessary (my math says 3.5x the size of the file) with eg the possibility of using up customers' data unnecessarily (see also [Fetch #651](https://github.com/tonyofrancis/Fetch/issues/651) )
> 
> As a result, at this point we'd rather move forward with just using Fetch's SEQUENTIAL downloader rather than using its PARALLEL downloader. So I'm exploring what avenues we might have for doing that. Obviously I could build from my own fork of RNBD with the downloadertype changed, but it's not my first choice. I was hoping there might be a way to pass an argument from the RN side, to change the downloader type that gets selected in the RNBackgroundDownloaderModule() routine.

Hi
Sorry for the long reply
Yeah, set property on JS side to choose between `sequential` and `parallel` downloader is preferred. I'll do it in a few days

Saw your commit here

https://github.com/paxproinc/react-native-background-downloader/commit/41c87651f5a39ef9c6ed65cac70317e253199ff4

**Comment by willxy** [comment]
Awesome, thanks.

**Comment by kesha-antonov** [comment]
Fixed with this release:

https://github.com/kesha-antonov/react-native-background-downloader/releases/tag/2.8.1

`sequential` used by default. Also you can change downloader type with `initDownloader` method

**Comment by willxy** [comment]
Awesome, thank you!
