### ISSUE TITLE
iOS: taskConfig is randomly nil

### ISSUE THREAD

**Issue by uzegonemad** [kesha-antonov/react-native-background-downloader#19]
### Is this a bug report, a feature request, or a question?
Bug Report

### Have you followed the required steps before opening a bug report?
- [x] I have reviewed [the documentation](https://github.com/EkoLabs/react-native-background-downloader/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/EkoLabs/react-native-background-downloader/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/EkoLabs/react-native-background-downloader/releases).

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?
iOS 17.4.1 (physical device)
(I haven't tested it on Android yet, but I will update this issue if I experience it on Android.)

### Is the bug related to the native implementation? (NSURLSession on iOS and Fetch on Android)
I'm unsure but I believe it's native RNBGD code.

### Environment
Environment:
```
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.5
    wanted: 0.73.5
```

```
"@kesha-antonov/react-native-background-downloader": "^3.1.2"
```

### Expected Behavior
When a task finishes downloading, `taskConfig` should not be nil.

### Actual Behavior
Randomly, **all** download tasks have a nil `taskConfig`. [See here for reference](https://github.com/kesha-antonov/react-native-background-downloader/blob/633c2fa34f4f595a48f7803e8fdecda567e6a1a7/ios/RNBackgroundDownloader.m#L358)

I discovered this because my downloads randomly aren't progressing (no downloadProgress event). To identify this, I added some additional debugging and checked the logs, and confirmed 

### Steps to Reproduce
I'm honestly not sure. I haven't been able to identify reproducible steps. I don't know if MMKV isn't persisting correctly or if there is some other issue.

If I'm able to identify reproducible steps I'll update here.

When this happens, closing & relaunching the app typically fixes the problem.

**Comment by uzegonemad** [comment]
FYI I haven't experienced this since I started testing #20. Merging that PR will likely close this issue

**Comment by kesha-antonov** [comment]
Fixed by https://github.com/kesha-antonov/react-native-background-downloader/pull/20
