### ISSUE TITLE
Build Failed react-native-background-downloader:compileDebugJavaWithJavac FAILED 

### ISSUE THREAD

**Issue by eramudeep** [kesha-antonov/react-native-background-downloader#2]
i did install the package with yarn

"react-native": "0.63.4",
"react-native-background-downloader": "github:kesha-antonov/react-native-background-downloader",

getting below error :

> Task :react-native-background-downloader:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.7.1/userguide/command_line_interface.html#sec:command_line_warnings
370 actionable tasks: 14 executed, 356 up-to-date
/Users/amusoftech/Documents/react_native/myproject/node_modules/react-native-background-downloader/android/src/main/java/com/eko/RNBackgroundDownloaderModule.java:362: error: lambda expressions are not supported in -source 7
        Thread th = new Thread(() -> {
                                  ^
  (use -source 8 or higher to enable lambda expressions)
1 error

**FAILURE: Build failed with an exception.**

* What went wrong:
Execution failed for task ':react-native-background-downloader:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s

**Need help**

 i did tried : multidex version upgrade none is worked

**Comment by alexjs87** [comment]
same problem

**Comment by kesha-antonov** [comment]
Which java do you use?
```java --version ```

**Comment by 765ggongchi** [comment]
same problem 
I use Java 11


openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

**Comment by kesha-antonov** [comment]
Closing since android side was rewritten on branch v3 https://github.com/kesha-antonov/react-native-background-downloader/tree/3.0.0
Please try it out

Also we should use newer version of java for recent RN
