### ISSUE TITLE
Crash (SIGSEGV(SEGV_MAPERR)) in completeHandler (RNBackgroundDownloader.m:319)

### ISSUE THREAD

**Issue by fivecar** [kesha-antonov/react-native-background-downloader#25]
### Is this a bug report, a feature request, or a question?

Bug Report

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - put an `x` character between the square brackets (`[]`).)

- [x] I have reviewed [the documentation](https://github.com/EkoLabs/react-native-background-downloader/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/EkoLabs/react-native-background-downloader/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/EkoLabs/react-native-background-downloader/releases).

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Reproduced on iOS, but I haven't deployed on Android so I'm not sure if it's platform specific.

### Is the bug related to the native implementation? (NSURLSession on iOS and Fetch on Android)

I believe so.

### Environment
Environment:
    "react": "18.2.0",
    "react-native": "^0.71.4",
    "@kesha-antonov/react-native-background-downloader": "^2.6.9"

Target Platform:
    iOS (12.4)

### Actual Behavior

This was detected in my production app via Instabug crash logging. Not sure what was going on when this happened. Wanted to file it here in case: a) anyone else has seen it, or b) someone knows the cause just by looking at the code.

```objective-c
RCT_EXPORT_METHOD(completeHandler:(nonnull NSString *)jobId
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)
{
    NSLog(@"[RNBackgroundDownloader] - [completeHandlerIOS]");
    if (storedCompletionHandler) {
        [[NSOperationQueue mainQueue] addOperationWithBlock:^{
            storedCompletionHandler();
            storedCompletionHandler = nil;
        }];
    } // This is line 319
    resolve(nil);
}
```

**Comment by andronixmd** [comment]
Same here. But i have this error in dev mode. Perhaps `storedCompletionHandler` is nil.

<img width="1127" alt="Screenshot 2023-05-30 at 11 42 12" src="https://github.com/kesha-antonov/react-native-background-downloader/assets/14835970/aacb4e04-cd98-432e-b54f-0c7930d4077e">

**Comment by kesha-antonov** [comment]
Hi,
thanks for the issue.

Added fix: [9b1b04b551d9bd98a0a58a2d1e60448686fd0507](https://github.com/kesha-antonov/react-native-background-downloader/commit/9b1b04b551d9bd98a0a58a2d1e60448686fd0507)

**Comment by fivecar** [comment]
Thanks, @kesha-antonov . Integrating now into build!

**Comment by kesha-antonov** [comment]
Should be fixed with this release:

https://github.com/kesha-antonov/react-native-background-downloader/releases/tag/2.8.1
