### ISSUE TITLE
Whether the notification bar supports displaying a progress bar

### ISSUE THREAD

**Issue by 951759534** [kesha-antonov/react-native-background-downloader#27]

**Comment by kesha-antonov** [comment]
I guess you're about android.
It doesn't for now
But it could be included in next version, I'm rewriting code with DownloadManager now

**Comment by kesha-antonov** [comment]
There's option now `isNotificationVisible`

https://github.com/kesha-antonov/react-native-background-downloader?tab=readme-ov-file#downloadoptions
