### ISSUE TITLE
This fork seems to cause main thread blocking and ANR issues on Android

### ISSUE THREAD

**Issue by mitchdowney** [kesha-antonov/react-native-background-downloader#29]
Hi @kesha-antonov, thanks for creating this fork. We used it in our app for about 5 months this year, but saw a huge spike in ANR issues. I can reproduce it consistently in our app when 1) install kesha-antonov/react-native-background-downloader, 2) start downloading 5+ large mp3 files, 3) start scrolling a scroll view up and down rapidly, 4) as soon as one of the episodes finish downloading, the scroll view freezes up for a couple seconds.

When I revert to the most recent version of the upstream RNBD, I can not reproduce this issue by following the same steps. Our ANRs have dropped dramatically since we started using the upstream version again.

I'm unfortunately not knowledgable about Android development, so I'm not sure what other insight I can offer. The changes between this fork and upstream seem pretty minimal, so it's perplexing what could be going wrong.

I spoke to @agates and he suggested maybe by turning on parallel fetch in this fork, perhaps it uses more system resources than the upstream?

For testing I am using a Pixel 4a, Android 13. If you have any questions or theories as to what could be going wrong I'd really appreciate it.

**Comment by kesha-antonov** [comment]
Hi

Yeah, there's quick fix for this with ANRs
I'll provide it tomorrow

**Comment by uzegonemad** [comment]
Hi @kesha-antonov,

I'm experiencing the same issue. Any help you can provide is greatly appreciated! Thanks so much for creating this fork.

**Comment by kesha-antonov** [comment]
Current patch will fix that for now:

`@kesha-antonov+react-native-background-downloader+2.7.2.patch`

```
diff --git a/node_modules/@kesha-antonov/react-native-background-downloader/android/src/main/java/com/eko/RNBackgroundDownloaderModule.java b/node_modules/@kesha-antonov/react-native-background-downloader/android/src/main/java/com/eko/RNBackgroundDownloaderModule.java
index d772c86..5d1752c 100644
--- a/node_modules/@kesha-antonov/react-native-background-downloader/android/src/main/java/com/eko/RNBackgroundDownloaderModule.java
+++ b/node_modules/@kesha-antonov/react-native-background-downloader/android/src/main/java/com/eko/RNBackgroundDownloaderModule.java
@@ -89,14 +89,14 @@ public class RNBackgroundDownloaderModule extends ReactContextBaseJavaModule imp
 
     OkHttpClient okHttpClient = new OkHttpClient.Builder().build();
     final Downloader okHttpDownloader = new OkHttpDownloader(okHttpClient,
-                Downloader.FileDownloaderType.PARALLEL);
+                Downloader.FileDownloaderType.SEQUENTIAL);
 
     loadConfigMap();
     FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this.getReactApplicationContext())
             .setDownloadConcurrentLimit(4)
             .setHttpDownloader(okHttpDownloader)
             .enableRetryOnNetworkGain(true)
-            .setHttpDownloader(new HttpUrlConnectionDownloader(Downloader.FileDownloaderType.PARALLEL))
+            .setHttpDownloader(new HttpUrlConnectionDownloader(Downloader.FileDownloaderType.SEQUENTIAL))
             .build();
     fetch = Fetch.Impl.getInstance(fetchConfiguration);
     fetch.addListener(this);
```

**Comment by uzegonemad** [comment]
Thank you! I'll implement this patch and see if it helps.

**Comment by kesha-antonov** [comment]
Should be fixed with this release:

https://github.com/kesha-antonov/react-native-background-downloader/releases/tag/2.8.1
