### ISSUE TITLE
Corrupt files on Android

### ISSUE THREAD

**Issue by sebastiangrebe** [kesha-antonov/react-native-background-downloader#3]
### Is this a bug report, a feature request, or a question?

Bug report

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - put an `x` character between the square brackets (`[]`).)

- [x] I have reviewed [the documentation](https://github.com/EkoLabs/react-native-background-downloader/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/EkoLabs/react-native-background-downloader/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/EkoLabs/react-native-background-downloader/releases).

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Android

### Is the bug related to the native implementation? (NSURLSession on iOS and Fetch on Android)

Not sure yet

(Write your answer here.)

### Environment

  Environment:
    React: 17.0.2
    React native: 0.66.0
    react-native-background-downloader: latest master

  Target Platform:
    Android (11.0)

### Expected Behavior

Downloading a PDF file should give a correct working PDF file

### Actual Behavior

On iOS all seems to work fine
On Android though the file that is downloaded has the correct size but actually is corrupt
Opening it on a normal PDF reader on phone or computer does not work

### Steps to Reproduce

Just download a random PDF

I believe it is somewhat related to OkHttpClient

**Comment by kesha-antonov** [comment]
> Downloaded episode playback stops after losing internet access podverse/podverse-rn#1314

Yeah,  @sebastiangrebe  please provide your code

**Comment by kesha-antonov** [comment]
Closing since android side was rewritten on branch v3 https://github.com/kesha-antonov/react-native-background-downloader/tree/3.0.0
Please try it out
