### ISSUE TITLE
DownloadTaskState does not include 'PENDING'

### ISSUE THREAD

**Issue by sjchristi** [kesha-antonov/react-native-background-downloader#3]
`DownloadTaskState` does not include 'PENDING' as a state, but I have found that this is a state that the DownloadTask is in sometimes (immediately after creating it).

**Comment by kesha-antonov** [comment]
Hi
Yes, we need to add it to the js 

If you can please submit PR

**Comment by kesha-antonov** [comment]
Fixed by https://github.com/kesha-antonov/react-native-background-downloader/pull/20
