### ISSUE TITLE
App Ui stuck in android while download start

### ISSUE THREAD

**Issue by Rbkyada** [kesha-antonov/react-native-background-downloader#32]
### Is this a bug report, a feature request, or a question?

Bug Report

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - put an `x` character between the square brackets (`[]`).)

- [x] I have reviewed [the documentation](https://github.com/EkoLabs/react-native-background-downloader/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/EkoLabs/react-native-background-downloader/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/EkoLabs/react-native-background-downloader/releases).

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?
The bug is specific to Android ( tested it on IOS working perfectly). I am testing on a Android Emulator & Real device with android version 13. I also run your example app facing same issue.

### Is the bug related to the native implementation? (NSURLSession on iOS and Fetch on Android)
It's unclear at this point.

### Environment

  Environment:
    React: ^18.2.0
    React native: ^0.72.4
    react-native-background-downloader: ^2.8.2

  Target Platform:
    Android (13.0)

### Expected Behavior

Ui should not get stuck while downloading starting.

### Actual Behavior

When i start downloading some time i face in android Ui freeze and some time app didn't response.

(Write what happened. Add logs!)

### Steps to Reproduce

After start download and do scroll in app. it will get stuck.

https://github.com/kesha-antonov/react-native-background-downloader/assets/68548417/5248967c-772b-4a46-8538-ebc3c41764aa

**Comment by kesha-antonov** [comment]
Hi

Should be fixed in 2.9.0 (from 06.11)

**Comment by Rbkyada** [comment]
@kesha-antonov  Thx
