### ISSUE TITLE
progressInterval error when use download 

### ISSUE THREAD

**Issue by mohamadjavad-alavy** [kesha-antonov/react-native-background-downloader#37]
when use ### _**download**_ app crashed with err progressInterval 
and app crash before run begin,.....,error 
and don`t show any error in cmd 
and latest log is ==>
**_ [RNBackgroundDownloader] download {"destination": "/storage/emulated/0/Download/file.zip", "id": "1", "metadata": {}, "url":fileLink}_**
![Screenshot 2023-12-24 171535](https://github.com/kesha-antonov/react-native-background-downloader/assets/67069847/ad9e2711-3195-4f17-a5ce-397614992230)

**Comment by kesha-antonov** [comment]
Hi
Which version do you use?

**Comment by mohamadjavad-alavy** [comment]
"@kesha-antonov/react-native-background-downloader": "^3.0.0-alpha.0"

use this version

**Comment by kesha-antonov** [comment]
Could you share parameters list that you use to download?

**Comment by mohamadjavad-alavy** [comment]
![Screenshot 2023-12-24 182243](https://github.com/kesha-antonov/react-native-background-downloader/assets/67069847/58e62b7f-01ed-46c0-88a4-b1b7355274e9)

**Comment by mohamadjavad-alavy** [comment]
"react-native": "^0.72.6"
 "@kesha-antonov/react-native-background-downloader": "^3.0.0-alpha.0",

**Comment by kesha-antonov** [comment]
Check [3.0.0-alpha.1](https://www.npmjs.com/package/@kesha-antonov/react-native-background-downloader/v/3.0.0-alpha.1)

**Comment by kesha-antonov** [comment]
Also see updated readme in `3.0.0` branch https://github.com/kesha-antonov/react-native-background-downloader/tree/3.0.0

**Comment by mohamadjavad-alavy** [comment]
that work for me with update to [3.0.0-alpha.1](https://github.com/kesha-antonov/react-native-background-downloader/releases/tag/3.0.0-alpha.1)

thank you **_@kesha-antonov_**
