### ISSUE TITLE
Downloader breaking every other time you reload in debugger

### ISSUE THREAD

**Issue by sjchristi** [kesha-antonov/react-native-background-downloader#4]
I'm running on ios simulator, and I noticed that every other time the app is reloaded, the downloader stops working.

It looks like this is being caused because there are two instances of the downloader allocated at once, and one of the instances which receives all the messages has an invalid bridge so none of the events are forwarded on to javascript.

I'm not sure why this is the case; it seems that when the app is reloaded, it only deallocates the instances of the module every other time.  Not sure if this is a lower level react native bug or something else.

Thought I'd raise this here in case anyone else is wondering why it seems to be breaking sometimes when developing.

**Comment by kesha-antonov** [comment]
Hi
Did you try on real device?

**Comment by sjchristi** [comment]
on a full release bulid i haven't noticed htis happening on device, but i have seen it on device with a debug build where you can reload your app dynamically from react native.

**Comment by kesha-antonov** [comment]
Yes, I noticed this problem also, maybe it's related to Fast Refresh
I will look into it

**Comment by kesha-antonov** [comment]
Fixed by https://github.com/kesha-antonov/react-native-background-downloader/pull/20
