### ISSUE TITLE
pause and resume don't work in Android 

### ISSUE THREAD

**Issue by mohamadjavad-alavy** [kesha-antonov/react-native-background-downloader#40]
In Android when pausing a task **STATE** of the task changed but the download continued 
and **Task.stop( )** working
_**### It does not give any error**_

-  "@kesha-antonov/react-native-background-downloader": "^3.0.0-alpha.1",
- "react": "18.2.0"
- "react-native": "^0.72.6",

**Comment by kesha-antonov** [comment]
Hi
Pause/resume not supported on Android because of DownloadManager

**Comment by kesha-antonov** [comment]
Updated readme

**Comment by mohamadjavad-alavy** [comment]
Thank you, do you know a solution for this? @kesha-antonov

**Comment by kesha-antonov** [comment]
More info: https://android-review.googlesource.com/c/platform/packages/providers/DownloadProvider/+/2089866

**Comment by mohamadjavad-alavy** [comment]
It was useful, thank you @kesha-antonov

**Comment by mohamadjavad-alavy** [comment]
It was useful, thank you @kesha-antonov

**Comment by kesha-antonov** [comment]
We could try this. Not sure if it would work

https://stackoverflow.com/a/55705541/3452513
