### ISSUE TITLE
[Documentation] Update Example for v3

### ISSUE THREAD

**Issue by uzegonemad** [kesha-antonov/react-native-background-downloader#41]
The example in the repo appears to still use v2 syntax. This should be updated for v3.

(I can try to handle this if I get free time within the next couple weeks, but if anyone else gets to it before me, that's perfectly fine.)

**Comment by kesha-antonov** [comment]
Hi
Would be cool to see the PR

**Comment by kesha-antonov** [comment]
I've updated Example to v3
