### ISSUE TITLE
Invalid value for visibility: 2 crash when downloading on android

### ISSUE THREAD

**Issue by zoriya** [kesha-antonov/react-native-background-downloader#42]
### Is this a bug report, a feature request, or a question?

bug report

### Have you followed the required steps before opening a bug report?

(Check the step you've followed - put an `x` character between the square brackets (`[]`).)

- [x] I have reviewed [the documentation](https://github.com/EkoLabs/react-native-background-downloader/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/EkoLabs/react-native-background-downloader/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/EkoLabs/react-native-background-downloader/releases).

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Android specific

### Is the bug related to the native implementation? (NSURLSession on iOS and Fetch on Android)

No

### Environment

React 18.2.0
React native 0.73.2
react-native-background-downloader: 3.0.1
target: android 14

### Expected Behavior

The app should not crash when downloading.

### Actual Behavior

When starting a download, the code requests to hide the notification (at https://github.com/kesha-antonov/react-native-background-downloader/blob/ec1a172ccab349a434fad4e8bb5acd69907bb0d0/android/src/main/java/com/eko/RNBackgroundDownloaderModule.java#L374C4-L374C66). This gives the error "Invalid value for visibility: 2" because the app does not have the permission to download without notification. According to [stackoverflow](https://stackoverflow.com/questions/9345977/downloadmanager-request-setnotificationvisibility-fails-with-securityexception), one need to add
```xml
<uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />
```
to the android manifest.

I see to potential fixes:
 - Add the above permission to the android manifest
 - Or make the notification visible.

I would personally prefer to have the notification visible, since that's what most users expects when a download is ongoing on android.

### Steps to Reproduce

Install react-native-background-downloader and run download() on android 14.

**Comment by kesha-antonov** [comment]
Hi
Thanks for the report

I think this should be configurable - show/hide notification - since in our app we download lots of files for lesson (audios, images) and this would not be useful for user imo

**Comment by relaxxpls** [comment]
@kesha-antonov Awesome work on this fork 🙌🏼

Please could you add `<uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />` to the README?

**Comment by zoriya** [comment]
I think this can be handled automatically by creating a module level AndroidManifest.xml (at least that's what other modules do for expo).

**Comment by kesha-antonov** [comment]
> I think this can be handled automatically by creating a module level AndroidManifest.xml (at least that's what other modules do for expo).

Yes, good idea
If you have please submit PR
Or I can add it tomorrow

**Comment by kesha-antonov** [comment]
Merged https://github.com/kesha-antonov/react-native-background-downloader/pull/43

**Comment by kesha-antonov** [comment]
> <uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />

Added to Manifest so you don't have to do it in your app

**Comment by kesha-antonov** [comment]
Released https://github.com/kesha-antonov/react-native-background-downloader/releases/tag/3.1.1
