### ISSUE TITLE
Apple privacy manifest file

### ISSUE THREAD

**Issue by yamade** [kesha-antonov/react-native-background-downloader#44]
Hello @kesha-antonov 

You may notice this announcement from Apple.
https://developer.apple.com/support/third-party-SDK-requirements/

I think react-native-background-downloader is using `NSUserDefaults`.
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278401
So I'm wondering if you have any plan to add a privacy manifest file sometime soon. Thank you!

**Comment by kesha-antonov** [comment]
Hi
Thanks for the notice!

I'll try to add it the upcoming days
Also PR appreciated

**Comment by kesha-antonov** [comment]
Released https://github.com/kesha-antonov/react-native-background-downloader/releases/tag/3.1.0
