### ISSUE TITLE
Incorrect type for setConfig

### ISSUE THREAD

**Issue by relaxxpls** [kesha-antonov/react-native-background-downloader#8]
https://github.com/kesha-antonov/react-native-background-downloader/blob/1f52afe3d4359d9c66f0216c3e89b1ae7a7a5f6e/index.d.ts#L12-L16

doesn't match

https://github.com/kesha-antonov/react-native-background-downloader/blob/1f52afe3d4359d9c66f0216c3e89b1ae7a7a5f6e/index.ts#L53

I believe it should instead be:
```ts
export interface Config {
  headers?: DownloadHeaders;
  progressInterval: number : null;
  isLogsEnabled?: boolean;
}

type SetConfig = (config: Config) => void;
```

Please update it 🙌🏼

**Comment by kesha-antonov** [comment]
Fixed by https://github.com/kesha-antonov/react-native-background-downloader/pull/20
