### ISSUE TITLE
Installation fails since prepublish script is executed on yarn add package

### ISSUE THREAD

**Issue by ajeanjean-vivlio** [kesha-antonov/react-native-background-downloader#9]
### Is this a bug report, a feature request, or a question?

Bug report.

### Have you followed the required steps before opening a bug report?

- [x] I have reviewed [the documentation](https://github.com/EkoLabs/react-native-background-downloader/blob/master/README.md) in its entirety, including the dedicated documentations :books:.
- [x] I have searched for [existing issues](https://github.com/EkoLabs/react-native-background-downloader/issues) and made sure that the problem hasn't already been reported.
- [x] I am using [the latest plugin version](https://github.com/EkoLabs/react-native-background-downloader/releases).

### Is the bug specific to iOS or Android? Or can it be reproduced on both platforms?

Both platforms.

### Is the bug related to the native implementation? (NSURLSession on iOS and Fetch on Android)

No.

### Environment

  Environment:
    React: 18.0.0
    React native: 0.69.7
    react-native-background-downloader: 2.4.2

  Target Platform:
    Android
    iOS 

  Yarn package manager version : 3.2.1

### Expected Behavior

To be able to install the package.

### Actual Behavior

When I try to install `react-native-background-downloader` as mentioned in the doc, the `prepublish` script is executed and the installation fails. Here are some logs:

```
Packing react-native-background-downloader@https://github.com/kesha-antonov/react-native-background-downloader.git#commit=8a9a8108b9f06b895404efb410a05784d386391a from sources
Using Yarn Classic for bootstrap. Reason: "__metadata" key not found in yarn.lock, must be a Yarn classic lockfile

➤ YN0000: Retrieving https://nightly.yarnpkg.com/latest.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-1.22.19.cjs
➤ YN0000: Done in 3s 554ms

yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning "@react-native-community/eslint-config > eslint-plugin-react@7.12.4" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0".
warning "@react-native-community/eslint-config > eslint-plugin-react-hooks@1.7.0" has incorrect peer dependency "eslint@^3.0.0 || ^4.0.0 || ^5.0.0 || ^6.0.0".
warning "@react-native-community/eslint-config > eslint-plugin-react-native@3.6.0" has incorrect peer dependency "eslint@^3.17.0 || ^4 || ^5".
warning " > react-native-fs@2.18.0" has unmet peer dependency "react-native-windows@*".
warning " > react-native-vector-icons@6.7.0" has unmet peer dependency "@react-native-community/toolbar-android@^0.1.0-rc.1".
[4/4] Building fresh packages...
$ jest && npm run lint
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
PASS __tests__/mainTest.js
  ✓ download function (2ms)
  ✓ begin event
  ✓ progress event (1ms)
  ✓ done event
  ✓ fail event (1ms)
  ✓ pause
  ✓ resume
  ✓ stop (1ms)
  ✓ checkForExistingDownloads (3ms)
  ✓ wrong handler type (12ms)

Test Suites: 1 passed, 1 total
Tests:       10 passed, 10 total
Snapshots:   0 total
Time:        6.907s
Ran all test suites.
npm WARN lifecycle The node binary used for scripts is /var/folders/2p/rjfh8z7146l4mgprbywpgzlr0000gn/T/yarn--1670945604725-0.9074015828000599/node but npm is using /Users/username/.nvm/versions/node/v14.18.2/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> react-native-background-downloader@2.4.2 lint /private/var/folders/2p/rjfh8z7146l4mgprbywpgzlr0000gn/T/xfs-ce9bde29
> eslint .

Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating

/private/var/folders/2p/rjfh8z7146l4mgprbywpgzlr0000gn/T/xfs-ce9bde29/index.js
  88:77  error  A space is required before '}'  object-curly-spacing

/private/var/folders/2p/rjfh8z7146l4mgprbywpgzlr0000gn/T/xfs-ce9bde29/lib/downloadTask.js
  21:47  error  Unnecessary { after 'if' condition  curly

/private/var/folders/2p/rjfh8z7146l4mgprbywpgzlr0000gn/T/xfs-ce9bde29/metro.config.js
  17:2  error  Extra semicolon  semi

/private/var/folders/2p/rjfh8z7146l4mgprbywpgzlr0000gn/T/xfs-ce9bde29/react-native.config.js
   5:18  error  Strings must use singlequote  quotes
   5:58  error  Missing trailing comma        comma-dangle
   8:20  error  Strings must use singlequote  quotes
   8:31  error  Missing trailing comma        comma-dangle
   9:8   error  Missing trailing comma        comma-dangle
  10:6   error  Missing trailing comma        comma-dangle
  11:4   error  Missing trailing comma        comma-dangle
  12:2   error  Extra semicolon               semi

✖ 11 problems (11 errors, 0 warnings)
  11 errors and 0 warnings potentially fixable with the `--fix` option.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-native-background-downloader@2.4.2 lint: `eslint .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-native-background-downloader@2.4.2 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2022-12-13T15_33_50_954Z-debug.log
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

I cloned the repo locally and used the `--fix` option and all lint errors were fixed automatically. But I think that `prepublish` script is deprecated ([see here](https://yarnpkg.com/package/prepublish)) and continue to caused some troubles as mentionned here : [prepublish is run on yarn add package](https://github.com/yarnpkg/yarn/issues/3209).

Do you think you can do something about it? please.

Thank you for your help.

**Comment by ajeanjean-vivlio** [comment]
Hello,

Today I have forked your repository, and run a simple : `yarn lint --fix`, then I pushed the fix to my own fork and the installation went well.

So I think you will be able to fix this in the next commit easily.

Thank you for your help.

**Comment by kesha-antonov** [comment]
> Hello,
> 
> Today I have forked your repository, and run a simple : `yarn lint --fix`, then I pushed the fix to my own fork and the installation went well.
> 
> So I think you will be able to fix this in the next commit easily.
> 
> Thank you for your help.

Yes, sorry for the delay.
I did the same and pushed a commit

**Comment by kesha-antonov** [comment]
I replaced `prepublish` with `prepublishOnly`

https://docs.npmjs.com/cli/v9/using-npm/scripts?v=true#prepare-and-prepublish
